import type { Transaction, TaxSummary } from "../types";
import { formatCurrency, getCategoryMeta, BRAND_NAME } from "../constants";

const NL = String.fromCharCode(10);

// Generate a plain-text CSV export (no external PDF lib needed)
export function generateCSV(transactions: Transaction[], currencySymbol: string): string {
  const headers = ["Date", "Type", "Category", "Amount", "Payment Method", "Note"];
  const rows = transactions.map((t) => {
    const cat = getCategoryMeta(t.category);
    return [
      t.date,
      t.type === "inflow" ? "Income" : "Expense",
      cat?.label ?? t.category,
      `${currencySymbol}${t.amount.toFixed(2)}`,
      t.paymentMethod.replace("_", " "),
      `"${t.note.replace(/"/g, '""')}"`,
    ].join(",");
  });
  return [headers.join(","), ...rows].join(NL);
}

// Generate a simple text Tax Summary report
export function generateTaxReport(summary: TaxSummary, currencySymbol: string): string {
  const line = "═══════════════════════════════════════";
  const sep = "───────────────────────────────────────";
  const lines = [
    line,
    `  ${BRAND_NAME} - Tax Summary`,
    `  Period: ${summary.period.label}`,
    line,
    "",
    `  Gross Income:       ${formatCurrency(summary.grossIncome, currencySymbol)}`,
    `  Total Expenses:     ${formatCurrency(summary.totalExpenses, currencySymbol)}`,
    `  Deductible Exp.:    ${formatCurrency(summary.deductibleExpenses, currencySymbol)}`,
    `  ${sep}`,
    `  Net Income:         ${formatCurrency(summary.netIncome, currencySymbol)}`,
    `  Estimated Tax:      ${formatCurrency(summary.estimatedTax, currencySymbol)}`,
    `  Net After Tax:      ${formatCurrency(summary.netAfterTax, currencySymbol)}`,
    "",
    `  Transactions:       ${summary.transactionCount}`,
    line,
    `  Generated by ${BRAND_NAME}`,
    `  ${new Date().toLocaleDateString()}`,
  ];
  return lines.join(NL);
}

// Trigger a file download in the browser
export function downloadFile(content: string, filename: string, mimeType: string = "text/csv") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}